name: expense_tracker
description: Simple Project where you can add your daily expenses and track them across categories.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dotted_line: ^3.2.2
  flutter:
    sdk: flutter
  intl: ^0.18.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
